# Generated by Django 4.2.1 on 2023-08-05 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_lead_sale_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='deposit_amount',
            field=models.IntegerField(blank=True, default=0, editable=False, null=True),
        ),
    ]
