# Generated by Django 4.2.1 on 2023-08-24 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_lead_deposit_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Numbers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'شماره دیتابیس',
                'verbose_name_plural': ' شماره های دیتابیس',
            },
        ),
    ]
