# Generated by Django 4.2.1 on 2023-08-25 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_numbers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Numbers',
            new_name='BankNumbers',
        ),
        migrations.AlterModelOptions(
            name='sales',
            options={'verbose_name': 'فروش', 'verbose_name_plural': ' فروش ها'},
        ),
    ]
