# Generated by Django 4.2.1 on 2023-08-25 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_rename_numbers_banknumbers_alter_sales_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='banknumbers',
            name='organisation',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='leads.userprofile'),
        ),
    ]
