# Generated by Django 4.2.1 on 2023-08-30 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0006_banknumbers_organisation'),
    ]

    operations = [
        migrations.AddField(
            model_name='banknumbers',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='leads.agent'),
        ),
    ]
