# Generated by Django 4.2.1 on 2023-09-01 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0010_userprofile_is_active_alter_user_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='is_active',
        ),
    ]
