# Generated by Django 4.2.1 on 2023-09-01 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0012_alter_user_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='alt_name',
            field=models.CharField(default='Persian Name', max_length=100),
        ),
    ]
