# Generated by Django 4.2.1 on 2023-09-07 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0014_alter_user_alt_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='leads.agent'),
        ),
        migrations.AlterField(
            model_name='banknumbers',
            name='number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
