# Generated by Django 4.2.1 on 2023-09-07 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0015_sales_agent_alter_banknumbers_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='date_assigned',
            field=models.DateField(blank=True, null=True),
        ),
    ]
