# Generated by Django 4.2.1 on 2023-09-07 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0016_lead_date_assigned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='date_assigned',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
