# Generated by Django 4.2.1 on 2023-09-08 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0018_alter_lead_date_assigned'),
    ]

    operations = [
        migrations.CreateModel(
            name='DuplicateToFollow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='leads.agent')),
                ('organisation', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='leads.userprofile')),
            ],
            options={
                'verbose_name': 'شماره\u200c پیگیری',
                'verbose_name_plural': 'شماره\u200cهای پیگیری',
            },
        ),
    ]
