# Generated by Django 4.2.1 on 2023-09-08 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0019_duplicatetofollow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duplicatetofollow',
            name='date_added',
            field=models.DateField(auto_now_add=True),
        ),
    ]
