# Generated by Django 4.2.1 on 2023-09-16 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0021_remove_lead_deposit_amount_remove_lead_sale_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='sale',
        ),
        migrations.AddField(
            model_name='lead',
            name='total_sales',
            field=models.IntegerField(blank=True, default=0, editable=False, null=True),
        ),
    ]
