# Generated by Django 4.2.1 on 2023-09-16 19:28

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0023_historicalsales'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.agent')),
            ],
        ),
        migrations.RemoveField(
            model_name='sales',
            name='agent',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='lead',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='total_sales',
        ),
        migrations.DeleteModel(
            name='HistoricalSales',
        ),
        migrations.DeleteModel(
            name='Sales',
        ),
        migrations.AddField(
            model_name='sale',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.lead'),
        ),
    ]
