# Generated by Django 4.2.1 on 2023-09-16 19:35

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0025_lead_total_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='deposit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='sale',
            name='total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
