# Generated by Django 4.2.1 on 2023-09-17 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0027_historicalsale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalsale',
            name='deposit',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='deposit',
        ),
    ]
