# Generated by Django 4.2.1 on 2023-09-18 00:25

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0028_remove_historicalsale_deposit_remove_sale_deposit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsale',
            name='amount',
            field=models.DecimalField(decimal_places=0, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='historicalsale',
            name='total',
            field=models.DecimalField(decimal_places=0, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='sale',
            name='amount',
            field=models.DecimalField(decimal_places=0, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='sale',
            name='total',
            field=models.DecimalField(decimal_places=0, default=Decimal('0.00'), max_digits=10),
        ),
    ]
