# Generated by Django 4.2.1 on 2023-09-20 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0029_alter_historicalsale_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsale',
            name='organisation',
            field=models.ForeignKey(blank=True, db_constraint=False, default='1', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='leads.userprofile'),
        ),
        migrations.AddField(
            model_name='sale',
            name='organisation',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='leads.userprofile'),
        ),
    ]
