# Generated by Django 4.2.1 on 2023-09-22 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0030_historicalsale_organisation_sale_organisation'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='source',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
