# Generated by Django 4.2.1 on 2023-09-23 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0032_alter_agent_options_alter_banknumbers_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='is_team_leader',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('members', models.ManyToManyField(related_name='teams', to='leads.agent')),
            ],
        ),
    ]
