# Generated by Django 4.2.1 on 2023-09-24 06:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0034_team_organisation'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='leaders',
            field=models.ManyToManyField(related_name='lead_teams', to=settings.AUTH_USER_MODEL),
        ),
    ]
