# Generated by Django 4.2.1 on 2023-09-24 07:29

from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0035_team_leaders'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='birthday',
            field=django_jalali.db.models.jDateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
