# Generated by Django 4.2.1 on 2023-09-24 09:46

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0036_lead_birthday_alter_team_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='converted_date',
            field=django_jalali.db.models.jDateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='date_assigned',
            field=django_jalali.db.models.jDateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='date_modified',
            field=django_jalali.db.models.jDateField(blank=True, null=True),
        ),
    ]
