# Generated by Django 4.2.1 on 2023-09-24 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0038_alter_lead_converted_date_alter_lead_date_assigned_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='chat_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='phone_number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
