# Generated by Django 4.2.1 on 2023-09-24 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0039_agent_chat_id_alter_lead_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='chat_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
