# Generated by Django 4.2.1 on 2023-09-24 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0040_alter_agent_chat_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='date_assigned',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
