# Generated by Django 4.2.1 on 2023-09-29 08:41

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models
import leads.models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0043_alter_agent_chat_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agent',
            options={'verbose_name': 'Agent', 'verbose_name_plural': 'Agents'},
        ),
        migrations.AlterModelOptions(
            name='banknumbers',
            options={'verbose_name': 'Database Number', 'verbose_name_plural': 'Database Numbers'},
        ),
        migrations.AlterModelOptions(
            name='duplicatetofollow',
            options={'verbose_name': 'Duplicate Followup', 'verbose_name_plural': 'Duplicate Followups'},
        ),
        migrations.AlterModelOptions(
            name='followup',
            options={'verbose_name': 'Follow-up', 'verbose_name_plural': 'Follow-ups'},
        ),
        migrations.AlterModelOptions(
            name='historicalsale',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Sale', 'verbose_name_plural': 'historical Sales'},
        ),
        migrations.AlterModelOptions(
            name='lead',
            options={'verbose_name': 'Lead', 'verbose_name_plural': 'Leads'},
        ),
        migrations.AlterModelOptions(
            name='sale',
            options={'verbose_name': 'Sale', 'verbose_name_plural': 'Sales'},
        ),
        migrations.AlterModelOptions(
            name='source',
            options={'verbose_name': 'Source', 'verbose_name_plural': 'Sources'},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name': 'Team', 'verbose_name_plural': 'Teams'},
        ),
        migrations.AlterField(
            model_name='agent',
            name='chat_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Chat ID'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='is_team_leader',
            field=models.BooleanField(default=False, verbose_name='Team Leader'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.userprofile', verbose_name='Organisation'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='banknumbers',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='leads.agent', verbose_name='Agent'),
        ),
        migrations.AlterField(
            model_name='banknumbers',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date Added'),
        ),
        migrations.AlterField(
            model_name='banknumbers',
            name='number',
            field=models.CharField(max_length=20, unique=True, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='banknumbers',
            name='organisation',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='leads.userprofile', verbose_name='Organisation'),
        ),
        migrations.AlterField(
            model_name='duplicatetofollow',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='leads.agent', verbose_name='Agent'),
        ),
        migrations.AlterField(
            model_name='duplicatetofollow',
            name='date_added',
            field=models.DateField(auto_now_add=True, verbose_name='Date Added'),
        ),
        migrations.AlterField(
            model_name='duplicatetofollow',
            name='number',
            field=models.CharField(max_length=20, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='duplicatetofollow',
            name='organisation',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='leads.userprofile', verbose_name='Organisation'),
        ),
        migrations.AlterField(
            model_name='followup',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=leads.models.handle_upload_follow_ups, verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='followup',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followups', to='leads.lead', verbose_name='Lead'),
        ),
        migrations.AlterField(
            model_name='followup',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='historicalsale',
            name='agent',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='leads.agent', verbose_name='Agent'),
        ),
        migrations.AlterField(
            model_name='historicalsale',
            name='amount',
            field=models.DecimalField(decimal_places=0, default=Decimal('0.00'), max_digits=10, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='historicalsale',
            name='date',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Date Added'),
        ),
        migrations.AlterField(
            model_name='historicalsale',
            name='lead',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='leads.lead', verbose_name='Lead'),
        ),
        migrations.AlterField(
            model_name='historicalsale',
            name='organisation',
            field=models.ForeignKey(blank=True, db_constraint=False, default='1', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='leads.userprofile', verbose_name='Organisation'),
        ),
        migrations.AlterField(
            model_name='historicalsale',
            name='total',
            field=models.DecimalField(decimal_places=0, default=Decimal('0.00'), max_digits=10, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='age',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Age'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='leads.agent', verbose_name='Agent'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='birthday',
            field=django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='Birthday'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='leads.category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='converted_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Converted Date'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='country',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date Added'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='date_assigned',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date Assigned'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Date Modified'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='feedback',
            field=models.TextField(blank=True, null=True, verbose_name='Feedback'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='first_name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='job',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Job'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='last_name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.userprofile', verbose_name='Organisation'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='phone_number',
            field=models.CharField(max_length=20, unique=True, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='leads.source', verbose_name='Source'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='state',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='total_sale',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Total Sales'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.agent', verbose_name='Agent'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='amount',
            field=models.DecimalField(decimal_places=0, default=Decimal('0.00'), max_digits=10, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date Added'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.lead', verbose_name='Lead'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='organisation',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='leads.userprofile', verbose_name='Organisation'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='total',
            field=models.DecimalField(decimal_places=0, default=Decimal('0.00'), max_digits=10, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='source',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Source Name'),
        ),
        migrations.AlterField(
            model_name='source',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.userprofile', verbose_name='Organisation'),
        ),
        migrations.AlterField(
            model_name='team',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='team',
            name='leaders',
            field=models.ManyToManyField(related_name='lead_teams', to=settings.AUTH_USER_MODEL, verbose_name='Leaders'),
        ),
        migrations.AlterField(
            model_name='team',
            name='members',
            field=models.ManyToManyField(related_name='teams', to='leads.agent', verbose_name='Members'),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Team Name'),
        ),
        migrations.AlterField(
            model_name='team',
            name='organisation',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='leads.userprofile', verbose_name='Organisation'),
        ),
        migrations.AlterField(
            model_name='user',
            name='alt_name',
            field=models.CharField(blank=True, default='Persian Name', max_length=100, null=True, verbose_name='Alternate Name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_agent',
            field=models.BooleanField(default=False, verbose_name='Agent'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_organisor',
            field=models.BooleanField(default=True, verbose_name='Organisor'),
        ),
        migrations.AlterField(
            model_name='user',
            name='rank',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, 'Education')], default=1, verbose_name='Rank'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
