# Generated by Django 4.2.1 on 2023-09-29 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0044_alter_agent_options_alter_banknumbers_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banknumbers',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.userprofile', verbose_name='Organisation'),
        ),
        migrations.AlterField(
            model_name='historicalsale',
            name='organisation',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='leads.userprofile', verbose_name='Organisation'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.userprofile', verbose_name='Organisation'),
        ),
    ]
