# Generated by Django 4.2.1 on 2023-09-30 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0045_alter_banknumbers_organisation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('override_chat_id', models.BooleanField(default=False)),
                ('chat_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
