# Generated by Django 4.2.1 on 2023-09-30 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0046_chatsetting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatsetting',
            name='chat_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
