# Generated by Django 4.2.1 on 2023-10-02 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0047_alter_chatsetting_chat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='proposed_price',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Proposed Price'),
        ),
        migrations.AddField(
            model_name='lead',
            name='registered_price',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Registered Price'),
        ),
    ]
