# Generated by Django 4.2.1 on 2023-10-09 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0050_alter_lead_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='telegram_token',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Telegram Token'),
        ),
    ]
