# Generated by Django 4.2.1 on 2023-10-15 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0052_userprofile_chat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='position',
            field=models.IntegerField(default='0', verbose_name='Position in Rank'),
        ),
        migrations.AlterField(
            model_name='team',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.userprofile', verbose_name='Organisation'),
        ),
    ]
