# Generated by Django 4.2.1 on 2023-10-15 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0053_agent_position_alter_team_organisation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agent',
            options={'ordering': ['user__rank', 'position'], 'verbose_name': 'Agent', 'verbose_name_plural': 'Agents'},
        ),
    ]
