# Generated by Django 4.2.1 on 2023-10-15 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0054_alter_agent_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='is_available_for_leads',
            field=models.BooleanField(default=True, verbose_name='Available for Leads'),
        ),
    ]
