# Generated by Django 4.2.1 on 2023-10-15 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0056_alter_lead_phone_number_alter_lead_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organisation', to='leads.userprofile'),
        ),
    ]
