# Generated by Django 4.2.1 on 2023-10-16 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0057_alter_category_organisation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banknumbers',
            name='number',
            field=models.CharField(max_length=20, verbose_name='Phone Number'),
        ),
        migrations.AlterUniqueTogether(
            name='banknumbers',
            unique_together={('number', 'organisation')},
        ),
    ]
