# Generated by Django 4.2.1 on 2023-10-31 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0059_lead_low_quality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rank',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, 'Education')], default=1, verbose_name='Rank'),
        ),
    ]
