# Generated by Django 4.2.1 on 2023-11-27 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0061_telegrammessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegrammessage',
            name='organisation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='leads.userprofile', verbose_name='Organisation'),
            preserve_default=False,
        ),
    ]
