# Generated by Django 4.2.1 on 2023-11-28 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0062_telegrammessage_organisation'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegrammessage',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
