# Generated by Django 4.2.1 on 2024-01-22 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0063_telegrammessage_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_register_agent',
            field=models.BooleanField(default=False, verbose_name='Register Agent'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_team_user',
            field=models.BooleanField(default=False, verbose_name='Team User'),
        ),
    ]
