# Generated by Django 4.2.1 on 2024-01-22 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0064_user_is_register_agent_user_is_team_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rank',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, 'Education')], default=1, null=True, verbose_name='Rank'),
        ),
    ]
